FROM node:16.13.2-slim

WORKDIR /usr/src/app

COPY ./example-frontend .
EXPOSE 5000
ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm install && \
    npm install -g serve && \
    npm run build && \
    useradd -m frontuser && \
    chown frontuser .

USER frontuser

CMD ["serve", "-s", "-l", "5000", "build"]

