FROM node:fermium-alpine3.15

WORKDIR /usr/src/app

COPY ./example-frontend .
EXPOSE 5000
ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm install && \
    npm install -g serve && \
    adduser -D frontuser && \
    chown frontuser . && \
    npm run build

USER frontuser

CMD ["serve", "-s", "-l", "5000", "build"]

