version: '3'

services:

    logging-service:
        image: devopsdockeruh/simple-web-service:ubuntu
        build: .
        volumes:
            - ./log:/usr/src/app/text.log
        container_name: logging-service
