version: '3.7'

services:
  ts-dev-env:
    build: ./app
    command: npm start
    ports: 
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
      - ./app/node_modules:/usr/src/app/node_modules
    container_name: ts-dev-env

volumes:
  node_modules:
