FROM node:16.13.2-slim as front-build

WORKDIR /usr/src/app

COPY ./example-frontend .
ENV REACT_APP_BACKEND_URL=http://localhost:8080

EXPOSE 5000

RUN npm install && \
    npm run build && \
    npm install -g serve

CMD ["serve", "-s", "-l", "5000", "build"]
