version: '3.5'

services:
    front:
        image: dcfront
        build: .
        ports:
            - 5000:5000
        container_name: dc-front
    back:
        image: dcback
        build: .
        ports:
            - 8080:8080
        container_name: dc-back
        environment:
            - POSTGRES_USER=postgris
            - POSTGRES_PASSWORD=secretpassword
            - POSTGRES_HOST=psql
            - REDIS_HOST=redis
        depends_on:
            - psql
    psql:
        image: postgres:13.3-alpine
        restart: unless-stopped
        container_name: psql-db
        environment:
            - POSTGRES_USER=postgris
            - POSTGRES_PASSWORD=secretpassword
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        container_name: redis-db

