version: '3.5'

services:
    front:
        image: dcfront
        ports:
            - 5000:5000
        container_name: dc-front

    back:
        image: dcback
        ports:
            - 8080:8080
        container_name: dc-back
        environment:
            POSTGRES_PASSWORD: secretpassword
            POSTGRES_HOST: psql-db
            REDIS_HOST: redis-db

    psql:
        image: postgres:13.3-alpine
        restart: unless-stopped
        container_name: psql-db
        environment:
            POSTGRES_PASSWORD: secretpassword

    redis:
        image: redis
        ports:
            - 6379:6379
        container_name: redis-db
